service: bug-hunting # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1

functions:
  nuxt:
    handler: handler.render
    events:
      - http: 
          path: /
          method: ANY
      - http: 
          path: /{proxy+}
          method: ANY