service: ci-cd-sample
 
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
 
functions:
  app:
    handler: handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'